"""企业热点服务 RPC 契约；真实 SDK 实现通过依赖注入接入。"""

from app.clients.enterprise.baseline import (
    BaselineMetricKey,
    MetricBaselinePage,
    MetricBaselineQueryRequest,
    MetricBaselineRow,
    MetricBaselineWarehouseRpc,
    RpcHotNewsBaselineProvider,
)
from app.clients.enterprise.behavior_data import (
    BehaviorEventPage,
    BehaviorEventQueryRequest,
    BehaviorEventRow,
    BehaviorWarehouseRpc,
    BehaviorWatermarkRequest,
    BehaviorWatermarkResponse,
    RpcBehaviorDataSource,
)
from app.clients.enterprise.common import (
    DefaultRpcCallContextProvider,
    EnterpriseRpcAuthenticationError,
    EnterpriseRpcError,
    EnterpriseRpcRateLimitError,
    EnterpriseRpcRequestError,
    EnterpriseRpcResponseError,
    EnterpriseRpcTimeoutError,
    EnterpriseRpcUnavailableError,
    RpcCallContext,
    RpcCallContextProvider,
    RpcDeadlineBudget,
    RpcResponseMeta,
)
from app.clients.enterprise.dependencies import (
    EnterpriseHotNewsAdapterConfig,
    EnterpriseHotNewsAdapters,
    EnterpriseHotNewsRpcClients,
    build_enterprise_hot_news_adapters,
)
from app.clients.enterprise.model_gateway import (
    StructuredModelGatewayRpc,
    StructuredModelRequest,
    StructuredModelResponse,
    StructuredModelUsage,
)
from app.clients.enterprise.news_content import (
    NewsContentBatchRequest,
    NewsContentBatchResponse,
    NewsContentRow,
    NewsContentRpc,
    RpcNewsContentRepository,
)
from app.clients.enterprise.related_news import (
    RelatedNewsBatchRequest,
    RelatedNewsBatchResponse,
    RelatedNewsCandidate,
    RelatedNewsQuery,
    RelatedNewsQueryResult,
    RelatedNewsRetrievalRpc,
    RpcRelatedNewsSearchClient,
)

__all__ = [
    "BaselineMetricKey",
    "BehaviorEventPage",
    "BehaviorEventQueryRequest",
    "BehaviorEventRow",
    "BehaviorWarehouseRpc",
    "BehaviorWatermarkRequest",
    "BehaviorWatermarkResponse",
    "DefaultRpcCallContextProvider",
    "EnterpriseHotNewsAdapterConfig",
    "EnterpriseHotNewsAdapters",
    "EnterpriseHotNewsRpcClients",
    "EnterpriseRpcAuthenticationError",
    "EnterpriseRpcError",
    "EnterpriseRpcRateLimitError",
    "EnterpriseRpcRequestError",
    "EnterpriseRpcResponseError",
    "EnterpriseRpcTimeoutError",
    "EnterpriseRpcUnavailableError",
    "MetricBaselinePage",
    "MetricBaselineQueryRequest",
    "MetricBaselineRow",
    "MetricBaselineWarehouseRpc",
    "NewsContentBatchRequest",
    "NewsContentBatchResponse",
    "NewsContentRow",
    "NewsContentRpc",
    "RpcBehaviorDataSource",
    "RelatedNewsBatchRequest",
    "RelatedNewsBatchResponse",
    "RelatedNewsCandidate",
    "RelatedNewsQuery",
    "RelatedNewsQueryResult",
    "RelatedNewsRetrievalRpc",
    "RpcCallContext",
    "RpcCallContextProvider",
    "RpcDeadlineBudget",
    "RpcHotNewsBaselineProvider",
    "RpcNewsContentRepository",
    "RpcRelatedNewsSearchClient",
    "RpcResponseMeta",
    "StructuredModelGatewayRpc",
    "StructuredModelRequest",
    "StructuredModelResponse",
    "StructuredModelUsage",
    "build_enterprise_hot_news_adapters",
]
