"""Deterministic FastGPT-compatible HTTP stub for the hermetic E2E stack.

This is test infrastructure, not a model implementation.  It accepts the
small OpenAI-compatible request shape used by :class:`FastGPTClient`, returns
a strict ``HotNewsAnalysisReport``, and records only bounded call metadata so
the E2E driver can prove which immutable App profile was executed.
"""

from __future__ import annotations

import asyncio
import json
from collections import deque
from datetime import UTC, datetime
from typing import Any
from uuid import uuid4

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse

from app.schemas.hot_news import (
    AnalysisReason,
    HotNewsAnalysisInput,
    HotNewsAnalysisReport,
    OperationSuggestion,
)


app = FastAPI(title="NewsAgent FastGPT E2E Stub", version="1.0")
_calls: deque[dict[str, Any]] = deque(maxlen=1000)
_calls_lock = asyncio.Lock()
_next_sequence = 1


def build_e2e_report(
    analysis_input: HotNewsAnalysisInput,
) -> HotNewsAnalysisReport:
    """Build a validator-safe report strictly from trusted input fields."""

    components = analysis_input.score_components.model_dump()
    top_component = max(components, key=components.__getitem__)
    dominant_driver = (
        "insufficient_data"
        if analysis_input.hot_score < 0.2
        else top_component
    )
    metrics = analysis_input.metrics
    return HotNewsAnalysisReport(
        news_id=analysis_input.news_id,
        trend_assessment=(
            f"E2E deterministic report: hot_score={analysis_input.hot_score:.4f}, "
            f"ctr={metrics.ctr:.4f}."
        ),
        dominant_driver=dominant_driver,
        attention_reasons=[
            AnalysisReason(
                reason_type="metric",
                statement=(
                    f"{top_component} is the largest deterministic score "
                    "component in the supplied input."
                ),
                metric_keys=[f"{top_component}_component", "hot_score"],
                evidence_news_ids=[],
                confidence=1.0,
                certainty="observed",
            )
        ],
        related_contexts=[],
        operation_suggestions=[
            OperationSuggestion(
                action="Keep this synthetic item in the E2E observation set.",
                rationale="The request is an isolated pipeline acceptance run.",
                priority="low",
                metric_keys=["hot_score"],
                evidence_news_ids=[],
            )
        ],
        evidence_news_ids=[],
        applied_memory_ids=[],
        limitations=[
            "This response is generated by a deterministic E2E stub, not a model."
        ],
        overall_confidence=1.0,
    )


@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/e2e/calls")
async def list_calls(after_sequence: int = 0) -> dict[str, Any]:
    if after_sequence < 0:
        raise HTTPException(
            status_code=422,
            detail="after_sequence cannot be negative",
        )
    async with _calls_lock:
        return {
            "calls": [
                dict(item)
                for item in _calls
                if item["sequence"] > after_sequence
            ],
            "latest_sequence": _next_sequence - 1,
        }


@app.post("/e2e/reset")
async def reset_calls() -> dict[str, int]:
    async with _calls_lock:
        cleared = len(_calls)
        _calls.clear()
    return {"cleared": cleared}


@app.post("/api/v1/chat/completions")
async def chat_completions(request: Request) -> JSONResponse:
    global _next_sequence
    try:
        payload = await request.json()
        if not isinstance(payload, dict):
            raise ValueError("request root must be an object")
        app_id = _required_string(payload, "appId")
        variables = payload.get("variables")
        if not isinstance(variables, dict):
            raise ValueError("variables must be an object")
        mode = _required_string(variables, "mode")
        if mode != "hot_news_analysis":
            raise ValueError(f"unsupported E2E mode: {mode}")
        messages = payload.get("messages")
        if not isinstance(messages, list) or len(messages) != 1:
            raise ValueError("exactly one input message is required")
        message = messages[0]
        if not isinstance(message, dict):
            raise ValueError("message must be an object")
        raw_input = _required_string(message, "content")
        analysis_input = HotNewsAnalysisInput.model_validate_json(raw_input)
    except (KeyError, TypeError, ValueError) as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    report = build_e2e_report(analysis_input)
    request_id = f"fastgpt-e2e-{uuid4()}"
    async with _calls_lock:
        sequence = _next_sequence
        _next_sequence += 1
        _calls.append(
            {
                "sequence": sequence,
                "request_id": request_id,
                "app_id": app_id,
                "mode": mode,
                "news_id": analysis_input.news_id,
                "analysis_policy_version": (
                    analysis_input.analysis_policy_version
                ),
                "called_at": datetime.now(UTC).isoformat(),
            }
        )

    body = {
        "choices": [
            {
                "message": {
                    "role": "assistant",
                    "content": report.model_dump_json(),
                }
            }
        ],
        "usage": {
            "prompt_tokens": 1,
            "completion_tokens": 1,
            "total_tokens": 2,
            "test_stub": True,
        },
    }
    return JSONResponse(body, headers={"x-request-id": request_id})


def _required_string(values: dict[str, Any], key: str) -> str:
    value = values[key]
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{key} must be a non-empty string")
    return value.strip()
